### ISSUE TITLE
Brand Entity를 추가를 해서 브랜드 별로 아이템 보여주기 기능 추가

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/JunPaka_Shop#105]
### Comment
아이템이랑 OneToMany로 연관 지어진 Brand(Entity)를 추가를 합니다.
아이템 추가 기능에서 Brand를 선택을 할 수 있게 설정을 합니다.

브랜드 별로 아이템을 볼 수 있는 기능을 추가합니다.

### ToDo

- [x] Brand 엔티티를 추가합니다.(Id, brandName, brandComment,  openDate,  count)
- [x] Brand를 추가할 수 있는 html 생성
- [x] brandFormDto, brandRepository, brandService, brandController 생성
- [x] create 기능 구현
- [x] 테스트
- [x] 관계 성립 -> 기존 데이터에 추가
- [x] ItmeFormDto에 추가 및 Valid 설정(@NotBlank)
- [x] ItemFormDto에서 Brand도 추가할 수 있게 설정을 위해서 itemForm.html(View Template) 수정
- [x] 테스트
- [x] ItemDetail.html에 BrandName 추가
- [x] ItemDetail.html 에서 Brand Name을 선택을 하면 Brand Tab으로 넘어 갈 수 있게 설정
- [x] brandMain.html을 만들어서 Brand 별로 보여주기(브랜드 이름, 브랜드 이미지, 브랜드 설명, 전체 브랜드 아이템-페이징 사용)

**Comment by wnstjd5408** [comment]
Form 조금 더 수정
