### ISSUE TITLE
검색기능 구현

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/JunPaka_Shop#115]
### Comment
#83  을 설정 후에 아이템을 검색을 할 수 있는 기능 구현합니다. 검색 시 아이템 이름으로 검색하면 아이템이 나오고, Type( 세부 분류)로 검색하면 그에 대한 카테고리가 나올 수 있게 추천, Brand(브랜드) 이름으로 검색 시 브랜드 관련된 아이템이 보일 수 있게 합니다.

### TODO

- [ ] Service에 검색 기능 구현
- [ ] QueryDsl 설정
- [ ] template 수정 -> itemList.html
- [ ] 검색 쿼리 테스트
- [ ] 통합 테스트
