### ISSUE TITLE
Update 기능,UI css, item 수정 시 브랜드 추가

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/JunPaka_Shop#117]
### Comment
다양한 기능을 업데이트 합니다.

### TODO

- [x] brandMain.html에 스크롤 바를 없애기
- [x] itemForm.html에서 아이템 수정 시 브랜드 추가
- [x] header.html 에 사이트 이름 수정
- [x] itemDetail.html에 판매중 안보이게 하기 -> 품절일 때만
- [x]  itemDetail.html 상품 설명 위에다가 텍스트 추가
