### ISSUE TITLE
Pagination을 0번째부터가 1번째부터 보여주는걸로 변경

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/JunPaka_Shop#17]
### Comment
List 목록을 12개씩 보여주는게 아니고 16개씩 보여주는 걸로 변경, 그리고 Pagination의 첫 번호를 '1'로 설정을 합니다.
로고 부분  클릭시 URL을 메인 페이지로 이동시킵니다.

### TODO

- [x] 목록 개수 변경
- [x] Pagination 번호 변경
- [x] 로고 URL 링크 설정
