### ISSUE TITLE
Flower - flower 세부 내용 이미지 출력

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/JunPaka_Shop#27]
### Comment
Flower의 세부적인 내용에 더미 이미지에서 판매되는 서버에 저장되어 있는 이미지 링크로 대체합니다.

### TODO

- [x]  FileImageRepository에 메서드 추가
- [x] fileImageService 추가 및 수정
- [x] FlowerService 추가 및 수정
- [x] Controller 수정
- [x] flower.html 수정
- [x] 테스트
